name: Update Coverage on Pull Request

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK, Scala, and SBT
      uses: olafurpg/setup-scala@v5
      with:
        java-version: adopt@1.13
    - name: Analyze coverage
      run: sbt clean coverage +test
    - name: Update coverage report 
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: sbt coverageReport coveralls
