name: Run Tests on Push

on: [push] 

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        java: [ 8, 11, 13 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1  
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: adopt@1.${{ matrix.java }}
    - name: Run tests
      run: sbt +test
